### ISSUE TITLE
连接5G wifi的时候老是提示密码错误？2.4G没有问题。。。

### ISSUE THREAD

**Issue by HL1u** [qiqco/Dell-Latitude-7390-Hackintosh#1]
连接5G wifi的时候老是提示密码错误？2.4G没有问题。。。
然后就是type-c接口好像只能连接u盘使用。。

另外能更新驱动库以及Opencore到0.79吗？

**Comment by qiqco** [comment]
你的无线网卡型号是什么
这个type-c能否进行图像输出我也不知道
这电脑是别人的，我只是提供引导服务，到时候我会联系别人测试一下

**Comment by HL1u** [comment]
哥们，搞定了。哈哈。无线网卡是因为路由器频道问题，好像对于低频的5G频道会出现密码无法设置问题。我把路由器的5G固定在高频道161，就一切ok了。速度也还可以。
另外typec的接口设置了一下，可以输出视频信息了。不然容易出问题。
而且测试链接magsafe也可以使用。。。

感谢。。如果有足够时间，希望更新一下oc8，以及里面的驱动。。。

**Comment by qiqco** [comment]
请问你可以提供你修改过的USB配置文件吗，此电脑不是我的，每次进行调试都很麻烦，而且我也不知道效果。OC0.8.0应该在4月30号或者五月初更新，我现在在学校更新不了

**Comment by HL1u** [comment]
哥们，我用公司的电脑在整，结果我们那个破软件调试的时候把系统搞崩溃了，我全盘格式化了。现在啥都没剩下了。。。哎。
________________________________
发件人: qiqco ***@***.***>
发送时间: 2022年4月23日 11:32
收件人: qiqco/Dell-Latitude-7390-Hackintosh ***@***.***>
抄送: HL1u ***@***.***>; Author ***@***.***>
主题: Re: [qiqco/Dell-Latitude-7390-Hackintosh] 连接5G wifi的时候老是提示密码错误？2.4G没有问题。。。 (Issue #1)


请问你可以提供你修改过的USB配置文件吗，此电脑不是我的，每次进行调试都很麻烦，而且我也不知道效果。OC0.8.0应该在4月30号或者五月初更新，我现在在学校更新不了

―

**Comment by qiqco** [comment]
那你现在还装有macOS吗

**Comment by HL1u** [comment]
很想装，但是最近忙得不行，公司准备做工业端的读码，所以忙的不行，没那么多时间调试。。。所以。。。
