### ISSUE TITLE
为啥外接显示器的时候合上笔记本后，屏幕还亮着？不息屏？也不会睡眠

### ISSUE THREAD

**Issue by HL1u** [qiqco/Dell-Latitude-7390-Hackintosh#2]
如题，有啥解决办法吗？通常情况下是一般都是用外接的显示器。

即使不接显示器也不会睡眠和息屏。。。。

**Comment by qiqco** [comment]
正在解决

**Comment by qiqco** [comment]
<img width="949" alt="截屏2022-07-25 14 18 00" src="https://user-images.githubusercontent.com/69421869/180710793-2538b2ca-ecb1-4745-ad62-0227c0fc99fc.png">
这好像是特性，因为我采取了这种方式来修复睡眠的
